version: '3.8'

services:
  futura:
    image: pelpsi/futura-frontend 
    restart: always
    container_name: futura-frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - futura-backend

  futura-backend:
    image: pelpsi/futura-backend
    restart: always
    container_name: futura-backend
    volumes:
      - futura-db:/app
    ports:
      - "8080:8080"

volumes:
  futura-db:

